# Generated by Django 2.1 on 2018-08-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
